theme: jekyll-theme-tactile
permalink: pretty
collections:
  projects:
    output: true
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: default
twitter_url: https://twitter.com/DhiiOS
gitter_url: https://gitter.im/Dhii/Lobby
contact_form_url: https://dhii.wufoo.com/forms/ziafhhh1qs33xc/
